### ISSUE TITLE
依存パッケージを各プロジェクトで保有できるようにする

### ISSUE THREAD

**Issue by Cj-bc** [Cj-bc/blib#32]
# 現状の問題点
- グローバルに一つのバージョンしか置けない
- バージョン管理ができない

# 解決策

package.yamlのような物を配置する

**Comment by Cj-bc** [comment]
# 一番簡単な方法

CSVで管理する

```csv
cj-bc/libblib, 0.3
niieani/bash-oo-framework, 2.0
```

# 利点

パースが楽、シンプル

# 欠点

「ライブラリの依存ライブラリ」の管理方法にならない

**Comment by Cj-bc** [comment]
yamlで管理してPackage型にするのはどうか


```yaml:package.yaml
name: libblib
description: core of bash package manager 'blib'
dependencies:
  - name: cj-bc/libtar
    version: 0.3
  - name: https://github.com/niieani/bash-oo-framework
    version: 2.0
```

```
class:Package() {
  public string name = ""
  array version = ()
  map dependencies

  Package::fromYaml() {
    [string] path
    Yaml yml = $(Yaml::fromFile path)
    Package pkg
    $var:pkg name = "$(Data.Yaml.FindKey 

  }
}


Package pkg=$(Package::loadYaml "package.yaml")
```
